---
# tasks file for timescaledb

- name: timescaledb | add GPG signing key
  become: true
  apt_key:
    url: "https://packagecloud.io/timescale/timescaledb/gpgkey"
    state: present
    validate_certs: true
  tags: install

- name: timescaledb | add official repository
  become: true
  apt_repository:
    repo: "deb https://packagecloud.io/timescale/timescaledb/ubuntu/ focal main"
    state: present
    filename: timescaledb
  register: timescaledb_repo
  tags: install

- name: timescaledb | udpate apt cache
  become: true
  when: timescaledb_repo.changed
  apt:
    update_cache: true
  tags: install

- name: timescaledb | establish dependencies
  become: true
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - timescaledb-2-postgresql-{{ postgresql_version }}
  tags: install

- name: timescaledb | check if timescaledb is already configured
  become: true
  become_user: "{{ zabbix_server_pgsql_login_user }}"
  shell: |
    set -o pipefail
    psql -d {{ zabbix_server_dbname }} -c "select extname from pg_extension;" | tail +3 | head -n -2
  args:
    executable: /bin/bash
  register: pg_extensions
  changed_when: false
  tags: configure

- when: "'timescaledb' not in pg_extensions.stdout"
  block:
    - name: timescaledb | configure timescaledb in 'postgresql.conf'
      become: true
      command: "timescaledb-tune --quiet --yes >> /etc/postgresql/{{ postgresql_version }}/main/postgresql.conf"
      tags: configure

    - name: timescaledb | restart postgresql
      become: true
      service:
        name: postgresql
        state: restarted

    - name: timescaledb | add timescaledb extension to postgresql database
      become: true
      become_user: "{{ zabbix_server_pgsql_login_user }}"
      command: 'psql -d {{ zabbix_server_dbname }} -c "CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;"'
      register: output
