---

- hosts: zabbix_database
  become: true
  tasks:
    - name: Update apt packages
      become: true
      apt:
        update_cache: yes
        cache_valid_time: 86400 #One day
    - name: Install required packaged  # acl package
      apt:
        name: "{{ item }}"
        state: present
      with_items: 
        - wget
        - python3-psycopg2
        - acl
    - name: Add Postgres apt-key
      apt_key:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        state: present
    - name: Add Postgres 14 repo
      apt_repository: 
        repo: 'deb http://apt.postgresql.org/pub/repos/apt focal-pgdg main'
        state: present
        filename: pgdg
        update_cache: yes
    - name: Install postgresql
      apt:
        name: postgresql-{{ postgresql_version }}
        update_cache: yes
      notify:
        - Enable Postgresql
  handlers:
    - name: Enable Postgresql
      systemd:
        name: postgresql
        enabled: yes
  # roles:
  #   - role: geerlingguy.postgresql
- name: Installing postgres-client on zabbix-server
  hosts: zabbix_server
  become: true
  tasks:
    - name: Add Postgres apt-key
      apt_key:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        state: present
    - name: Add Postgres 14 repo
      apt_repository: 
        repo: 'deb http://apt.postgresql.org/pub/repos/apt focal-pgdg main'
        state: present
        filename: pgdg
        update_cache: yes
    - name: Install postgresql-client
      apt:
        name: postgresql-client-{{ postgresql_version }}
        update_cache: yes

- hosts: zabbix_database
  become: true
  tasks:
    - name: "Change listen_addresses to bastion ip"
      ansible.builtin.lineinfile:
        path: /etc/postgresql/{{ postgresql_version }}/main/postgresql.conf
        regexp: "listen_addresses =" 
        line: "listen_addresses = '{{ listen_addresses_postgresql }}'" 
        state: present
    - name: Configure PostgreSQL. Set hosts in pg_hba.conf
      ansible.builtin.template:
        src: pg_hba.conf.j2 
        dest: /etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf
    - name: Restart postgresql
      service:
        name: postgresql
        state: restarted
    - name: "Install timescaledb"
      include_tasks: ubuntu_timescaledb.yml

- name: Installing Zabbix
  hosts: zabbix_server
  become: true
  collections:
    - community.zabbix

  roles:
    - role: zabbix_server
    - role: geerlingguy.apache
    - role: geerlingguy.php
    - role: zabbix_web

  post_tasks:
    - name: Create user group
      connection: local
      become: false
      register: api_create_user_group
      until: api_create_user_group is succeeded
      community.zabbix.zabbix_usergroup:
        server_url: "{{ zabbix_url }}"
        login_user: "{{ zabbix_api_user }}"
        login_password: "{{ zabbix_api_pass }}"
        name: ops
        state: present

    - name: 'Create an email mediatype with message templates'
      become: false
      connection: local
      register: api_create_mediatype
      until: api_create_mediatype is succeeded
      community.zabbix.zabbix_mediatype:
        name: "A: Ops email"
        server_url: "{{ zabbix_url }}"
        login_user: "{{ zabbix_api_user }}"
        login_password: "{{ zabbix_api_pass }}"
        type: 'email'
        smtp_email: 'ops@example.com'
        smtp_server: 'mail.example.com'
        smtp_helo: 'example.com'
        message_templates:
          - eventsource: triggers
            recovery: operations
            subject: "Problem: {EVENT.NAME}"
            body: "Problem started at {EVENT.TIME} on {EVENT.DATE}\r\nProblem name: {EVENT.NAME}\r\n"
          - eventsource: triggers
            recovery: recovery_operations
            subject: "Resolved: {EVENT.NAME}"
            body: "Problem resolved at {EVENT.TIME} on {EVENT.DATE}\r\nProblem name: {EVENT.NAME}\r\n"
          - eventsource: triggers
            recovery: update_operations
            subject: "Updated problem: {EVENT.NAME}"
            body: "{USER.FULLNAME} {EVENT.UPDATE.ACTION} problem at {EVENT.UPDATE.DATE} {EVENT.UPDATE.TIME}.\r\n"
          - eventsource: discovery
            recovery: operations
            subject: "Discovery: {DISCOVERY.DEVICE.STATUS} {DISCOVERY.DEVICE.IPADDRESS}"
            body: "Discovery rule: {DISCOVERY.RULE.NAME}\r\n\r\nDevice IP: {DISCOVERY.DEVICE.IPADDRESS}"
          - eventsource: autoregistration
            recovery: operations
            subject: "Autoregistration: {HOST.HOST}"
            body: "Host name: {HOST.HOST}\r\nHost IP: {HOST.IP}\r\nAgent port: {HOST.PORT}"

    - name: Deploy trigger action
      connection: local
      become: false
      register: api_create_trigger
      until: api_create_trigger is succeeded
      community.zabbix.zabbix_action:
        server_url: "{{ zabbix_url }}"
        login_user: "{{ zabbix_api_user }}"
        login_password: "{{ zabbix_api_pass }}"
        name: "A: Send alerts to Admin"
        event_source: 'trigger'
        state: present
        status: enabled
        esc_period: "60"
        conditions:
          - type: 'trigger_severity'
            operator: '>='
            value: 'Information'
        operations:
          - type: send_message
            subject: "Something bad is happening"
            message: "Come on, guys do something"
            media_type: 'Email'
            send_to_groups:
              - 'ops'

    - name: create of zabbix user.
      connection: local
      become: false
      register: api_create_user
      until: api_create_user is succeeded
      community.zabbix.zabbix_user:
        server_url: "{{ zabbix_url }}"
        login_user: "{{ zabbix_api_user }}"
        login_password: "{{ zabbix_api_pass }}"
        alias: vpoat
        name: vpoat
        surname: vpoat
        usrgrps:
          - ops
          - Zabbix administrators
        passwd: thisiskeep
        lang: en_US
        theme: blue-theme
        autologin: no
        autologout: '0'
        refresh: '30'
        rows_per_page: '200'
        after_login_url: ''
        user_medias:
          - mediatype: Email
            sendto: vpoat@example.com
            period: 1-7,00:00-24:00
            severity:
              not_classified: no
              information: yes
              warning: yes
              average: yes
              high: yes
              disaster: yes
            active: no
        type: Zabbix super admin
        state: present

    - name: Restart Apache
      service:
        name: apache2
        state: restarted
